Affirm/Magento2_Affirm

view/frontend/web/template/payment/form.html
=> Copy update

composer.json, etc/config.xml
Enhances analytics defaulted to enabled
=> Enhanced analytics (partnereng 1687)

etc/config.xml
Adding additional US territories
=> US territories (PARTNERENG-1630) 

view/frontend/web/js/model/aslowas.js
=> affirm refresh

Block/Promotion/AslowasAbstract.php, Model/Config/System/Source/Logo.php, Model/Plugin/Category/ViewAbstract.php, Model/Plugin/MiniCart/AsLowAs/ConfigPlugin.php
- Adding white as logo dropdown option
- Changing blue logo to default
=> white logo option

etc/adminhtml/system.xml
For mulitsite configuration show Private API key
=> Fix Missing Private API

Controller/Payment/Confirm.php, composer.json, etc/module.xml
Making master compatible for Magento 2.3
=> Magento 2.3

Model/AffirmCheckoutManager.php, etc/di.xml, view/frontend/web/js/model/affirm.js, view/frontend/web/template/payment/form.html
Allow Affirm the checkout with virtual products
PARTNERENG-2143
Added logic to lookup state when the state is missing
PARTNERENG-2306
=> Support Virtual and Missing state

Block/Onepage/ClearCart.php, view/frontend/layout/checkout_onepage_success.xml, view/frontend/templates/onepage/clearcart.phtml
Clears mini cart after succesful checkout
=> clear mini cart

Model/Observer/AddressFormat.php
Adding a fix for cart2quote extension
=> fix for cart2quote

Helper/AsLowAs.php, Model/Plugin/Product/ListProduct.php
adding a price on the template for category page
=> fix category page ALA

Gateway/Http/Client/ClientService.php, Gateway/Validator/Client/PaymentActionsValidator.php, Gateway/Validator/Client/PaymentActionsValidatorVoid.php, Gateway/Validator/CurrencyValidator.php, Logger/Handler.php, Logger/Logger.php, Model/Adminhtml/Observer/AfterShipmentSaveObserver.php, Model/AffirmCheckoutManager.php, Model/Plugin/Order/AddressSave/Edit.php, etc/di.xml
---
Updates logging
---
Updates logs in debug.log as well as payment.log
=> updates logging

composer.json, etc/module.xml
Version bump to 3.0.12
- Updates logging
- Updates enhanced analytics
=> version bump to 3.0.12

Gateway/Validator/Client/PaymentActionsValidator.php, Gateway/Validator/Client/PaymentActionsValidatorVoid.php, Gateway/Validator/CurrencyValidator.php, composer.json, etc/module.xml
Reverting the added logs to validator classes as it is causing dependency reference issues.
=> Hotfix update logging

composer.json, etc/config.xml, etc/module.xml
Inline Checkout will be disabled by default
Inline Checkout will be disabled by default
=> Inline default false

Gateway/Helper/Util.php, Gateway/Http/Client/ClientService.php, Gateway/Request/AbstractDataBuilder.php, Gateway/Request/CaptureRequest.php, Gateway/Validator/Client/PaymentActionsValidator.php, Model/Config.php, Model/Plugin/Payment/CanCapturePartial.php, composer.json, etc/adminhtml/system.xml, etc/config.xml, etc/di.xml, etc/module.xml
---
Partial Capture
---
Enable partial capture for Affirm payment method
Steps to test the feature:
1. Go to Configuration -> Sales -> Payment method -> Affirm
2. Select "Authorize" for Payment Action and "Yes" for Partial Capture
3. Place a test order with multiple items
4. Go to the order page in Orders -> click Invoice
5. Update Qty to Invoice 
4. Click "Submit Invoice" with "Capture Online" selected (default)
Error message display:
=> Partial Capture

composer.json, etc/module.xml
- Compatibility check with the latest release version (2.4.4)
=> version bump to 3.1.1

Model/Config.php, Model/Ui/ConfigProvider.php, etc/adminhtml/system.xml, i18n/fr_CA.csv, view/frontend/web/js/view/payment/method-renderer/affirm_gateway.js
---
FR Translation
---
* Adds French translation for admin and user interface
* Moves hardcoded strings from frontend JS to a backend model in order to support the `bin/magento i18n:collect-phrases` command/workflow.
=> FR translation

Model/Config.php
---
Update prod URL for Affirm.js
---
This PR updates the production url for Affirm.js
=> Update prod URL for Affirm.js

Model/Plugin/Payment/CanCapturePartial.php
---
Refactor accessing country code data from payment attribute
---
This PR makes it more explicit to access country code from the payment attribute.
=> Refactor accessing country code data from payment attribute

composer.json, etc/module.xml
---
name: Bump version to 3.3
---
Bumping version 3.3
support m2.4.6
1. Go to '...'
4. See error
=> 3.3 version bump

Block/Promotion/CartPage/Aslowas.php, Controller/Adminhtml/Rule.php, Gateway/Helper/Util.php, Gateway/Request/AbstractDataBuilder.php, Helper/Pixel.php, Model/Adminhtml/Observer/PredispatchObserver.php, Model/Observer/SetAffirmAnalyticsOnOrderSuccessPageView.php, Model/Observer/UpdateFinancingProgramOnLogin.php
---
name: PR Template
---
1. Go to '...'
4. See error
=> Fix missing pixel var

composer.json, etc/module.xml
---
Version bump 3.3.2
---
Hotfix - Removes a trailing comma
=> Version bump 3.3.2

Model/Config.php
---
Update prod URL for Affirm.js (cdn1)
---
This PR updates the production url for Affirm.js
=> Update prod URL for Affirm.js (cdn1)

composer.json, etc/module.xml
---
name: 3.3.3 Version Bump
---
Bumping to version 3.3.3 to include new listing changes and also updated global sandbox UD
1. Go to '...'
4. See error
=> 3.3.3 Version Bump

composer.json, etc/module.xml
---
name: 3.3.4 version bump
---
Bumping version so we can update the magento listing
1. Go to '...'
4. See error
=> 3.3.4 version bump

composer.json, etc/module.xml
---
name: version bump to 3.3.5
---
Features include split capture support for CA enabled merchants
Display french banners when locale is fr_CA
1. Go to '...'
4. See error
=> version bump to 3.3.5

Block/Onepage/AffirmButton.php, Gateway/Helper/Util.php, Gateway/Validator/Client/PaymentActionsValidator.php, Helper/FinancingProgram.php, Helper/Payment.php, Helper/Payment/Data.php, Helper/Rule.php, Model/Config.php, Model/ResourceModel/Rule/Collection.php, Model/Rule/Condition/Address.php, Model/Rule/Condition/Product/Subselect.php, Plugin/RestrictPaymentMethods.php, view/adminhtml/templates/affirm/error.phtml, view/adminhtml/templates/payment/info/edit.phtml, view/frontend/templates/onepage/button.phtml, view/frontend/templates/payment/info/edit.phtml, view/frontend/templates/pixel/confirm.phtml, view/frontend/templates/promotion/aslowasCart.phtml, view/frontend/templates/promotion/aslowasPDP.phtml, view/frontend/templates/promotion/bml.phtml
---
name: PHP Codesniffer linting
---
linting based on PHP codesniffer
1. Go to '...'
4. See error
=> PHP Codesniffer linting

Test/Mftf/ActionGroup/AdminAffirmEnableActionGroup.xml, Test/Mftf/ActionGroup/AdminAffirmPromoEnableActionGroup.xml, Test/Mftf/Page/AffirmPromoPage.xml, Test/Mftf/Section/AffirmConfigSettingsConfigSection.xml, Test/Mftf/Test/AdminAddMFP.xml, Test/Mftf/Test/EnableAffirm.xml, Test/Mftf/Test/EnableAffirmPromo.xml, Test/Mftf/Test/SeeALA.xml, Test/Mftf/Test/SeeAffirmCheckout.xml
---
name: Add MFTF test
---
Add a few test to our extension
1) Enable Affirm
2) Enable Promo Messages
3) Add MFP to product
4) Check if ALA is present on product page
5) Check if Affirm is a payment option on checkout
1. Go to '...'
4. See error
=> Add MFTF test

composer.json, etc/module.xml
---
name: Bumping to 4.0.6
---
Bumping to 4.0.6 to include several locale changes
[Fix : Define _affirm_config as global variable](https://github.com/Affirm/Magento2_Affirm/pull/140)
[GraphQl : fix save country_code in sales_order_payment](https://github.com/Affirm/Magento2_Affirm/pull/139)
[Fix Region code String instead of passing object](https://github.com/Affirm/Magento2_Affirm/pull/137)
1. Go to '...'
4. See error
=> Bumping to 4.0.6
