Model/Observer/IdentifyFinancingProgram.php
---
name: remove controller action
---
removing the use of controller action 
1. add affirm_fpid to the query string on the homepage.  affirm_fpid should be a financing program
2.checkout and make sure the above financing up program is on checkout
financing program on checkout
Magento is no longer supporting controller actions from the observer
=> remove controller action

view/frontend/templates/pixel/code.phtml, view/frontend/web/js/affirmPixel.js, view/frontend/web/js/affirmWidget.js, view/frontend/web/js/aslowasPDP.js, view/frontend/web/js/aslowasPLP.js, view/frontend/web/js/model/global.js
Removing jquery UI as it is not used on our functions
---
name: PR Template
---
1. check to see if there are no console errors caused by affirm on the product, catalog, and cart pages
No changes in behavior
Remove a library that is not being used
=> remove jquery UI

Api/InlineCheckoutInterface.php, Model/InlineCheckout.php, Model/Ui/ConfigProvider.php, composer.json, etc/adminhtml/system.xml, etc/di.xml, etc/module.xml, etc/webapi.xml, view/frontend/web/js/action/inline-checkout.js, view/frontend/web/js/view/payment/method-renderer/affirm_gateway.js, view/frontend/web/template/payment/form.html
---
name: Inline Checkout
---
Add Affirm value props on the checkout page when Affirm is selected
1. Enable inline messaging in Admin
2. Select Affirm as the payment method on checkout
3. See Affirm value props
Affirm value props appear when Affirm is selected as the payment method
=> add inline checkout

Model/InlineCheckout.php
Bugfix for PSE-502 500 error for inline api call on closing Affirm payment window
---
Fix for PSE-502
---
If you decide to cancel Affirm payment and come back on the checkout page, for some Magento versions it removes the shipping address hence causing an error on the address street index. This fix only fixes the indexing error so after populating the address inline checkout works again.
Magento shipping address not saved post page refresh on checkout [issue](https://support.magento.com/hc/en-us/articles/360025843552-Shipping-address-not-saved-post-page-refresh-on-checkout-) is known for 2.2.3 version, on cancelling the payment window it takes you back to the shipping page instead of checkout and the user needs to populate the address again.
=> Bug fix for PSE-502 500 error for inline api call on closing Affirm payment window

Block/Info.php, Gateway/Command/CaptureStrategyCommand.php, Gateway/Helper/Request/Action.php, Gateway/Http/Client/ClientService.php, Gateway/Request/AbstractDataBuilder.php, Gateway/Request/AuthorizationRequest.php, Gateway/Request/CaptureRequest.php, Gateway/Request/RefundRequest.php, Gateway/Request/VoidRequest.php, Gateway/Response/TransactionAuthorizeHandler.php, Gateway/Response/TransactionRefundHandler.php, Model/Adminhtml/Observer/AfterShipmentSaveObserver.php, Model/Plugin/Order/AddressSave/Edit.php, etc/di.xml, view/frontend/web/js/affirmPixel.js
Allowing Magento 2 extension to use [Transactions API](https://docs.affirm.com/affirm-developers/reference#merchant-transactions-api) which replaces the existing [Charges endpoints](https://docs.affirm.com/affirm-developers/reference#the-charge-object) while maintaining the same functionality. 
* Changed request URI paths for charge related actions (`api/v2/charges` -> `api/v1/transactions`) along with other parameter changes to use the Transactions API
* Updated references of `charge_id` variable name to `transaction_id` 
* Allow previous stored `charge_id` payment attribute to be accessible to maintain backward compatibilit
Place an order using Affirm payment and perform charge actions in admin mode (capture, void, update, refund, etc). Using developer mode, confirm the updated endpoint …
=> Transactions API 

Gateway/Helper/Request/Action.php, Gateway/Http/AbstractTransferFactory.php, Gateway/Http/TransferFactory.php, Gateway/Request/AbstractDataBuilder.php, Gateway/Request/CaptureRequest.php, Helper/Pixel.php, Model/Adminhtml/Observer/AfterShipmentSaveObserver.php, Model/Config.php, Model/Plugin/Order/AddressSave/Edit.php, etc/adminhtml/system.xml
---
Store level API keys
---
Allow Affirm API credentials to be configured on the store level scope instead of being set within the default configuration only.
Steps to test the proposed changes:
1. Go to Admin Stores -> Configuration
2. Click on Scope dropdown to access substores
3. Scroll down to Sales -> Payment methods -> Affirm
4. Uncheck "Use Website" next to API keys and mode inputs to configure
=> Store level API keys

Setup/Uninstall.php
---
Uninstall Script
---
Add uninstall script to remove custom eav attributes and drop Affirm tables added by InstallSchema class. 
Steps to test the changes:
1. Pull this change 
2. Go to a M2 instance root with Astound_Affirm module installed
3. Run `bin/magento setup:di:compile` (to make sure changes are compiled) and run `bin/magento module:uninstall Astound_Affirm` to test the uninstall script
Once uninstall command is complete, check M2 database and `eav_attributes` table to confirm the script ran properly (`select * from eav_attribute where attribute_code like '%affirm%' LIMIT 20;`)
=> Uninstall script

Block/Promotion/AslowasAbstract.php, Block/Promotion/Banners.php, Block/Promotion/CartPage/Aslowas.php
---
PHP 8 Support - Move optional parameters behind required parameters
---
PHP 8 now requires optional parameters to specified after any required arguments ([source](https://www.php.net/manual/en/functions.arguments.php)): 
`Note that any optional arguments should be specified after any required arguments, otherwise they cannot be omitted from calls.`
Install or update Affirm extension with the following commands in PHP 8.1 to verify successful compilation:
```
composer require affirm/magento2
composer update
php bin/magento setup:upgrade
php bin/magento setup:di:compile
```
=> PHP 8 Support

Gateway/Request/AbstractDataBuilder.php, Gateway/Request/CaptureRequest.php, Gateway/Request/RefundRequest.php, Gateway/Validator/Client/AbstractResponseValidator.php, Gateway/Validator/Client/PaymentActionsValidator.php, Plugin/SaveInvoiceAmountToCapture.php, Plugin/UpdateAuthMessage.php, Plugin/UpdatePrependMessage.php, etc/di.xml
---
Update Order Comment with Checkout Currency
---
Prior to the changes, order comments are automatically set during transaction operation by methods in classes such as `magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation`, `magento/module-sales/Model/Order/Payment/Operations/ProcessInvoiceOperation` and etc. These methods by default use base currency and not checkout currency when updating the order comments. 
1. The changes introduce plugin interceptors to replace the amount values in base currency to amount values in checkout currency (`Plugin/UpdateAuthMessage.php` and `Plugin/UpdatePrependMessage.php`). 
2. To support Partial Capture, the total amount needs to be obtained from the invoice object, and from the the gateway subjects. This required the usage of …
=> Update Order Comment with Checkout Currency

Model/InlineCheckout.php
---
Syntax error for PHP 7.4
---
Received below result from the code sniffer when submitting to Magento marketplace:
> 
> Errors listed below must be fixed and resubmitted to Marketplace.
> To prevent errors in the future please read our [technical standards documentation](https://github.com/magento/magento-coding-standard/wiki/Magento-Marketplace-Extensions-Verification).
> 
> File : /usr/share/eqp/PhpCodeSnifferTool/tmp/work/Model/InlineCheckout.php
> PHP syntax error: syntax error, unexpected ')', expecting variable (T_VARIABLE)
> severity : 10
> Line : 66
> Column : 1
> Source : Generic.PHP.Syntax.PHPSyntax
=> addresses syntax error

etc/di.xml
With affirm set to sandbox mode - trying to place an order split over 12 months, with no auto pay set, magento crashes with critical exception.
Error seems to be coming from invalid XML
Magento 2.4.4
PHP 8.1
Affirm 3.2.0
1. Add item to cart
2. checkout
3. Select Affirm
4. Turn off auto pay
5. select 12 months
6. Pay/complete
7. Get redirected back to magento
8. See error in var/log/
Doesn't crash, and order is successful.
Seems to be an issue with the XML
Allow successful payment through affirm
Stack trace:
`2022-08-23T14:32:48.817665+00:00] report.CRITICAL: Exception message: Missing required argument $action of Astound\Affirm\Gateway\Helper\Request\Action.
Trace: <pre>#1 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() …
=> Exception - Missing required argument $action of Astound\Affirm\Gateway\Helper\Request\Action

Model/Checkout.php
---
Double email confirmation fix
---
1. Place an order with Affirm payment method.
2. Receive double order confirmation through email.
Receive only one order confirmation
=> Double email confirmation fix

Model/Config.php
---
Hotfix: Fixes missing currency code error
---
This change fixes the following error:
```
Exception #0 (Exception): Notice: Undefined index: MXN in /var/www/html/app/code/Astound/Affirm/Model/Config.php on line 759
Exception #0 (Exception): Notice: Undefined index: MXN in /var/www/html/app/code/Astound/Affirm/Model/Config.php on line 759
<pre>#1 Astound\Affirm\Model\Config->getApiKeyNameByCurrency() called at [app/code/Astound/Affirm/Model/Config.php:318]
#2 Astound\Affirm\Model\Config->getPublicApiKey() called at [app/code/Astound/Affirm/Model/Config.php:696]
#3 Astound\Affirm\Model\Config->getAllAsLowAsConfig() called at [app/code/Astound/Affirm/Model/Plugin/MiniCart/AsLowAs/ConfigPlugin.php:59]
#4 Astound\Affirm\Model\Plugin\MiniCart\AsLowAs\ConfigPlugin->afterGetConfig() called at …
```
=> Hotfix: Fixes missing currency code error

Plugin/UpdatePrependMessage.php
A bug was discovered when doing partial refunds for other payment methods, in the notes section it would still show that the whole amount was refunded even though it was only partially refunded.  This was caused by a our before action.  We will now check the payment method to be affirm first before running
1. Do a partial refund for a non affirm order
2. Check the notes section to see that the whole amount was refunded even though the order was only partially refunded
To show the correct refunded amount in the orders notes section
=> Only Update for Affirm Payments

Block/System/Config/Form/Field/Date.php
---
name: Allow Affirm Promo configuration to be saved
---
Bug fix for Stores -> Configuration -> General -> Affirm Promos datepicker isn't loaded thus javascript breaks the page and prevents saving
1. In the Magento 2 admin, Go to 'Stores -> Configuration -> General -> Affirm Promos'
2. Bug occurs
- See Javascript error in the developer tools console
- Observe the save button doesn't function
- Observe the left hand navigation doesn't function
- Able to save configuration
- Able to use left hand navigation
- Datepicker would show for the `Start date for Financing Program value` and `End date for Financing Program value` fields
```
Uncaught TypeError: jQuery(...).datepicker is not a function
```
Allow the configuration to be saved in the Magento admin as …
=> Bug Fix: datepicker on promo configuration page prevents saving of configuration

Plugin/UpdatePrependMessage.php
---
name: Fix constant
---
Fixing defined constant
1. Go to '...'
4. See error
=> fix constant

Gateway/Http/Client/ClientService.php, Model/Adminhtml/Observer/AfterShipmentSaveObserver.php, Model/Plugin/Order/AddressSave/Edit.php
---
name: Use Laminas instead of Zend for REST APIs
---
Zend Framework was deprecated but Magento was still including this package.  Starting with Magento 2.4.6 Zend is no longer an included package in Magento.  With this change we will need to use laminas to make request.
1. Checkout with Affirm
2. Ensure that Auth, Capture, Refund, and Void is still working
Checkout, Auth, Capture, Refund, and Void will work as normal.  Changes only affect how the request call was made
=> use laminas instead of zend

Gateway/Command/CaptureStrategyCommand.php, Gateway/Validator/Client/PaymentActionsValidatorCaptureFailVoid.php, etc/di.xml
---
name: Void order when capture fails
---
For merchants that have auth and capture enabled.  We will void the order if last invoice amount is not set when trying to capture.  This will stop active orders on Affirm when there is no order in Magento
1. Go to '...'
4. See error
=> Void on capture Fail

Controller/Adminhtml/Rule/Edit.php, Controller/Adminhtml/Rule/Save.php
---
name: Remove Zend Filter
---
Remove deprecated zend filter with new magento filger
1. Go to '...'
4. See error
=> remove zend filter

Model/Config.php
We typically load AFJS through the `cdn1` subdomain. This change removes an extra 301 hop.
=> Update afjs URL to use cdn1

Model/Config.php, etc/module.xml
---
name: Bump 3.3.1
---
Version bump uses CDN instead of www.  to decrease latency
1. Go to '...'
4. See error
=> Version Bump to 3.3.1

Gateway/Command/CaptureStrategyCommand.php
---
name: PR Template
---
1. Use php 7.3 version and do composer require
2. After installing do `bin/magento setup:upgrade`
3. It should show error like below
4. Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /vendor/affirm/magento2/Gateway/Command/CaptureStrategyCommand.php on line 78
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /vendor/affirm/magento2/Gateway/Command/CaptureStrategyCommand.php on line 78
5. See error
There should not be any error like that.
=> Removed trailing comma to support PHP < 8

Model/Config.php, view/frontend/templates/promotion/bml.phtml
---
name: French Banners
---
When locale is fr_CA it will load french banners.  All other locales will load english banners
1. Go to '...'
4. See error
=> French Banners

Model/Config.php, Model/Plugin/Payment/CanCapturePartial.php
---
name: Split Capture CA
---
Allow CA merchants to do split capture
1. Go to '...'
4. See error
=> Split Capture CA

Gateway/Http/Client/ClientService.php, Gateway/Validator/Client/PaymentActionsValidator.php, Gateway/Validator/Client/PaymentActionsValidatorCaptureFailVoid.php, Gateway/Validator/Client/PaymentActionsValidatorVoid.php, Helper/ErrorTracker.php
---
[[PSE-2398](https://jira.team.affirm.com/browse/PSE-2398)] -  Log Errors to Error Tracker
---
Errors that fail locally are hard to track and monitor since they are not sent back to Affirm. By sending a request containing error information back to our Affirm endpoint, we will be able to observe errors through Chronosphere, Kibana, and Rollbar to help alert us of any issues that arise.
We don't expect to encounter exceptions in our flow so to reproduce this behavior, we have to intentionally throw one. I've been editing the code to throw an exception.
1. Throw an exception/create a false validation result in ClientService or the PaymentActionValidator, respectively
2. Check Chronosphere, Kibana, and Rollbar for error
- On Kibana, check for evid: …
=> [PSE-2398] - Log Errors to Error Tracker

Helper/ErrorTracker.php
---
Add telesales version to error tracker
---
Add telesales version if flag is marked for error tracker
Throw an exception in telesales where we send an error back to Affirm. These calls to the error tracker will include the telesales version.
Going to send Affirm telesales version in case of telesales error.
=> Add telesales version to Affirm error tracker

Model/Plugin/Order/Create.php, Model/Plugin/Order/EditOrder.php, Model/Plugin/Payment/Checks/CanUseForCountry.php, Model/Plugin/Product/ListProduct.php
---
name: rename around method names
---
Adobe wants to restrict the use of around methods.  Instead we should be using before or after when possible
1. Go to '...'
4. See error
=> rename around method names

Gateway/Validator/Client/PaymentActionsValidatorVoid.php
Problem of class was simple:
constructor, used there never called parent's constructor, so Depenedcy Injections of parent constructor was ingored. This lead to `$this->createResult(...` at 71 line, causing error, because it calls parent's `createResult` from `Magento\Payment\Gateway\Validator\AbstractValidator`, and it uses `$this->resultInterfaceFactory`, which is unexpeted null, because parent constuctor never set up this value, because of parent::__construc() was never called, and DI's values wass never passed there.
---
name: Fix PaymentActionsValidatorVoid class
---
Fixed constructor, that was cause error: 
[2024-05-08T07:54:28.859710+00:00] main.CRITICAL: Error: Call to a member function create() on null in .../vendor/magento/module-payment/Gateway/Validator/AbstractValidator.php:43 …
=> Fixed Astound\Affirm\Gateway\Validator\Client\PaymentActionsValidatorVoid class

composer.json, etc/module.xml
---
Support for PHP83
---
Updating composer to support PHP 8.3 install
1. Go to '...'
4. See error
=> Support for PHP83

Model/Plugin/Order/EditOrder.php, composer.json
---
name: Fix beforeExecute EditOrder
---
Fixing beforeExecute for EditOrder.
Function now returns controller back to original function
1. Go to '...'
4. See error
=> Fix beforeExecute EditOrder

Block/Info.php, view/adminhtml/templates/payment/info/edit.phtml
Today, if a customer places an order on the `CA` environment, the link to the `US` domain is used, which causes a 404 error.
The objective of this MR is to correct this bug by using the correct domain according to the country, as well as:
**Production :**
- For `CA`:  https://www.affirm.ca/dashboard/#/details/XXX
- For `US`: https://www.affirm.com/dashboard/#/details/XXX
**Sandbox :**
- For `CA`:  https://www.sandbox.affirm.ca/dashboard/#/details/XXX
- For `US`: https://www.sandbox.affirm.com/dashboard/#/details/XXX
=> Admin Support canada order dashboard URL

Model/Observer/AddressFormat.php
If region Id exist the model should be loaded by ->load() method instead of loadByCode().
---
name: Load Region Model Correctly
---
Load Region Model Correctly
I discovered this issue after installing this module. After this module installed new order mails are could not been sent.
And got this exception log
`[2024-08-29T12:14:58.711410+00:00] .CRITICAL: Error: Object of class Magento\Directory\Model\Region could not be converted to string in /home/magento/vendor/magento/module-directory/Model/ResourceModel/Region.php:143
Stack trace:
#0 /home/magento/vendor/magento/module-directory/Model/Region.php(59): Magento\Directory\Model\ResourceModel\Region->loadByCode()
#1 /home/magento/vendor/affirm/magento2/Model/Observer/AddressFormat.php(48): …
=> Fix : Load Region Model Correctly
